### ISSUE TITLE
Missing controller

### ISSUE THREAD

**Issue by codejunction** [matlus/SignalRAndWorkerServices-GettingStarted#1]
Hi @matlus i think the controller is missing from the source repo.
followed your yt video. but if you can update the repo.

**Comment by matlus** [comment]
Hi @codejunction. Thank you for writing in. What controller are you seeing missing exactly? There are no MVC or Web API controllers in this solution/project. This is the same solution I used during the video.

**Comment by codejunction** [comment]
Yes, I later realized it was a razor app not an MVC app.
